vehicle_model_zoo = [
    "resnet50_normal",
    "resnet101_normal",
    "resnet152_normal",
    "wresnet50_normal",
    "vgg13_normal",
    "vgg16_normal",
    "vgg19_normal",
    "densenet121_normal",
    "densenet161_normal",
    "densenet201_normal",
    # "convs_normal",
    # "convb_normal",
    # "convl_normal",
    "swins_normal",
    "swinb_normal",
    "swinl_21k",
    "vits_normal",
    "vitb_normal",
    "vitl_normal",
    # "t2t14_normal",
    # "t2t19_normal",
    # "t2t24_normal",
    "xcits_normal",
    "xcits_sota",
    # "xcitm_normal",
    # "xcitm_sota",
    "xcitl_normal",
    "xcitl_sota",
]
